name: Deploy to AWS

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to S3
      uses: aws-actions/s3-sync@v1
      with:
        args: --delete
        bucket: ${{ secrets.S3_BUCKET }}
        region: ${{ secrets.AWS_REGION }}
        source: ./dist   # 构建输出目录（Hexo/VuePress/React等）

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v1
      with:
        distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        paths: "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
